### ISSUE TITLE
Enable remaining rt-tests

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#417]
The following 4 tests were enabled. The maintainter was only enabling these 4 in this PRs, so we had enabled these 4 only as the first step.
cyclictest
cyclicdeadline
rtla-osnoise
rtla-timerlat

Enable the following tests as well:
pi-stress
pmqtest
ptsematest
rt-migrate-test
signaltest
sigwaittest
svsematest

**Comment by igaw** [comment]
The reason why only four tests are enabled is to keep the runtime in the same ball park is it was before. Sure, it would be good to run the other tests too. What would be an acceptable runtime for the tests? I am asking because most of these tests should be run for a longer period to catch outliers. If we run them only for a minute it, it is basically a smoke tests.  This is also okay but it wont give me any warm fuzzy feeling if the RT patched kernel is behaving any good. 

So if the goal is to have a quick smoke test run, I'd say enable them and let them run for a minute. We could define one test case to run a bit longer which has potential to catch outliers, e.g. rtla-osnoise with a couple of different workloads.

**Comment by musamaanjum** [comment]
I'll enable the remaining tests as well.

As far as the duration of tests is concerned, the current running time is 60 seconds by default. We can have a look at the load on the devices and increase the running time of all these tests. Or we can also increase the running time of rtla-osnoise as a starting point and go from there.

@nuclearcat @igaw what could be the realistic and reasonable time for these tests? Would 5 or 10 minutes be enough?

cc: @helen-fornazier

**Comment by nuclearcat** [comment]
Yes, i think 10 minutes as upper limit are fine.
