### ISSUE TITLE
Create Grafana dashboard on top of production instances for Tast test results

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-project#462]
The dashboard should show all the tast-tests executed. There should be the ability to select a certain tast suite and only get results for that suite.

We need this dashboard on top of the production instance.

**Comment by helen-fornazier** [comment]
@musamaanjum which kind of filters do you need?

If you go to this link: https://grafana.kernelci.org/d/OKXc44EIz/home?orgId=1&var-origin=maestro&var-tree=mainline&var-branch=All&var-test_path_regex=tast&var-platform=%25&var-config=%25&var-datasource=default 

It shows all the Tast tests, you can check which trees there are more errors in the Overview section, and you can expand the build or test section, and there is a table listing all the executions.

If you want to see a specific test suite, you can write it on the "Path" variable on top.

Let me know if this suites your needs. Sometimes this board takes too long because it loads everything, so if you have more filters we can work on a lighter dashboard.

**Comment by musamaanjum** [comment]
Closing as no extra dashboard is required. The results must be checked on the existing dashboard using stricter criteria.
